### ISSUE TITLE
status_warn_fill (\E92B) has extraneous dot

### ISSUE THREAD

**Issue by harrv** [MicroFocus/ias-icons#27]
The status_warn_fill icon (\E92B) has an extraneous dot outside of the circle at the top-right of the icon that its siblings, status_ok_fill (\E925) and status_error_fill (\E928) do not have.

https://microfocus.github.io/ias-icons/#!/app/icons/tile

**Comment by ldchrist** [comment]
I believe this is now fixed in v1.0.4. Thank you.
